run_name: connor-bcp
image: mosaicml/pytorch:1.12.1_cu116-python3.9-ubuntu20.04
cluster: r8z2
gpu_num: 8
gpu_type: a100_40gb

integrations:
  - integration_type: git_repo
    git_repo: cojennin/bestcp
    git_branch: main
    pip_install: -r requirements.txt

command: |
  cd benchmarks/llm
  python convert_c4.py --out_root ./my-copy-c4 --splits val
  composer main.py /mnt/config/parameters.yaml \
    train_loader.dataset.split=val \
    progress_bar=false \
    run_name=$COMPOSER_RUN_NAME